import { ROSTER, type CreatureId } from "../engine";

/* Translated epithet + ability blurb per critter. English is the source of
 * truth (lives in the engine's ROSTER); the other languages override here.
 * Anything missing falls back to English. */

type Entry = { epithet: string; blurb: string };
type Lang = Record<string, Entry>;

const ES: Lang = {
  boulderpup: { epithet: "Firme", blurb: "Sus celdas son permanentes. Nada puede moverlas ni quitarlas." },
  mossback: { epithet: "Bosque viejo", blurb: "Cada una de sus celdas cuenta el doble para dominar una región." },
  slumberstone: { epithet: "Asentándose", blurb: "Duerme un turno mientras se asienta, luego se vuelve permanente." },
  mudpaw: { epithet: "Arraigado", blurb: "Al congelarse el juego, las regiones empatadas donde tengas una de sus celdas caen a tu favor." },
  slatetusk: { epithet: "Roca madre", blurb: "Sus celdas son permanentes y almacena 1 de energía al colocarse." },
  lichenox: { epithet: "Avance lento", blurb: "Duerme un turno al arraigar, luego cada celda suya cuenta el doble para dominar una región." },
  breezefinch: { epithet: "Voluble", blurb: "Sus celdas pueden saltar a una celda vacía adyacente." },
  tumbleweed: { epithet: "Rodante", blurb: "Sus celdas pueden saltar y almacena 1 de energía al colocarse para pagar saltos." },
  glidewing: { epithet: "Planeador", blurb: "Sus celdas pueden saltar, y sus saltos también pueden ir en diagonal." },
  driftmink: { epithet: "Deslizante", blurb: "Sus celdas pueden saltar y almacena 2 de energía al colocarse." },
  galepup: { epithet: "Ventoso", blurb: "Sus celdas pueden saltar, también en diagonal, y almacena 1 de energía al colocarse." },
  dandypuff: { epithet: "Ingrávido", blurb: "Sus celdas pueden saltar, y cualquier eliminación solo lo aparta un turno en vez de quitarlo." },
  snoozemouse: { epithet: "Adormilado", blurb: "Duerme un turno, luego despierta y bloquea cualquiera de sus regiones que lideres." },
  fogkit: { epithet: "Brumoso", blurb: "Duerme dos turnos, luego despierta y bloquea cualquiera de sus regiones que lideres. Un zarpazo tardío." },
  dozderling: { epithet: "Recolector somnoliento", blurb: "Almacena 3 de energía, duerme un turno, luego despierta y bloquea cualquiera de sus regiones que lideres." },
  drowsivole: { epithet: "Medio dormido", blurb: "Duerme un turno, luego despierta y bloquea tus regiones. Ya despierto, gana 3 de energía cuando el rival bloquea una región donde está." },
  lullabird: { epithet: "Canción suave", blurb: "Duerme un turno, luego despierta y bloquea tus regiones. Al congelarse, las regiones empatadas donde está caen a tu favor." },
  dreamnewt: { epithet: "Adormeciéndose", blurb: "Almacena 2 de energía, duerme dos turnos, luego despierta y bloquea tus regiones. Un zarpazo lento y fuerte." },
  nutsquirrel: { epithet: "Recolector", blurb: "Almacena 2 de energía al colocarse." },
  acorncache: { epithet: "Acaparador", blurb: "Almacena 4 de energía al colocarse." },
  sunbeetle: { epithet: "Paciente", blurb: "Almacena 1 de energía, y 3 más cada vez que el rival bloquea una región donde está." },
  tallykit: { epithet: "Contador", blurb: "Almacena 2 de energía por cada mina que tengas." },
  sunmoth: { epithet: "Al sol", blurb: "Almacena 3 de energía al colocarse." },
  emberfinch: { epithet: "Yesca", blurb: "Almacena 2 de energía, y 3 más cada vez que el rival bloquea una región donde está." },
  pricklehog: { epithet: "Espinoso", blurb: "El rival no puede bloquear una región completándola mientras tengas una celda ahí." },
  shellclam: { epithet: "Primera luz", blurb: "Al congelarse el juego, las regiones empatadas donde tengas una celda caen a tu favor." },
  barknewt: { epithet: "Rebrotante", blurb: "Un Topo no puede quitarlo, y cualquier otra eliminación solo lo aparta un turno." },
  thornpod: { epithet: "Protector", blurb: "Paga energía para poner una mina (hasta 3): el rival no puede colocar ahí hasta limpiarla, y cuenta como celda tuya." },
  quillhog: { epithet: "Erizado", blurb: "Cada una de tus minas cuenta el doble para dominar una región." },
  barkmole: { epithet: "Atrincherado", blurb: "El rival no puede bloquear una región completándola mientras tengas una celda ahí, y cualquier eliminación solo lo aparta un turno." },
  swiftwren: { epithet: "Inquieto", blurb: "Al colocar este dígito puedes pagar energía para colocar un segundo dígito el mismo turno." },
  digmole: { epithet: "Excavador", blurb: "Paga energía para colocar este dígito sobre un dígito no permanente del rival en una región disputada, eliminándolo." },
  wildlark: { epithet: "Ascendente", blurb: "Paga energía para colocar este dígito ignorando la regla de fila, columna y caja (pero no para completar una región)." },
  bombkit: { epithet: "Chisporroteante", blurb: "Tus minas cuestan 2 menos de poner." },
  joltjay: { epithet: "Nervioso", blurb: "Al colocar este dígito puedes pagar energía para colocar un segundo el mismo turno, y almacena 1 de energía al colocarse." },
  sparkpaw: { epithet: "Estático", blurb: "Paga energía para colocar este dígito ignorando las reglas, o para colocarlo sobre un dígito no permanente del rival en una región disputada, eliminándolo." },
};

const FR: Lang = {
  boulderpup: { epithet: "Inébranlable", blurb: "Ses cases sont permanentes. Rien ne peut les déplacer ni les retirer." },
  mossback: { epithet: "Vieille forêt", blurb: "Chacune de ses cases compte double pour tenir une région." },
  slumberstone: { epithet: "En installation", blurb: "Dort un tour en s'installant, puis devient permanent." },
  mudpaw: { epithet: "Enraciné", blurb: "Au gel du jeu, les régions à égalité où vous tenez une de ses cases basculent en votre faveur." },
  slatetusk: { epithet: "Roche-mère", blurb: "Ses cases sont permanentes et il stocke 1 énergie à la pose." },
  lichenox: { epithet: "Lente emprise", blurb: "Dort un tour en prenant racine, puis chacune de ses cases compte double pour tenir une région." },
  breezefinch: { epithet: "Volage", blurb: "Ses cases peuvent sauter vers une case vide adjacente." },
  tumbleweed: { epithet: "Roulant", blurb: "Ses cases peuvent sauter ; il stocke 1 énergie à la pose pour payer des sauts." },
  glidewing: { epithet: "Planeur", blurb: "Ses cases peuvent sauter, et ses sauts peuvent aussi être en diagonale." },
  driftmink: { epithet: "Effleurant", blurb: "Ses cases peuvent sauter et il stocke 2 énergie à la pose." },
  galepup: { epithet: "Bourrasque", blurb: "Ses cases peuvent sauter, en diagonale aussi, et il stocke 1 énergie à la pose." },
  dandypuff: { epithet: "Sans poids", blurb: "Ses cases peuvent sauter, et tout retrait ne fait que l'écarter un tour au lieu de le prendre." },
  snoozemouse: { epithet: "Somnolent", blurb: "Dort un tour, puis se réveille et verrouille toute région où vous menez." },
  fogkit: { epithet: "Brumeux", blurb: "Dort deux tours, puis se réveille et verrouille toute région où vous menez. Une frappe différée." },
  dozderling: { epithet: "Butineur endormi", blurb: "Stocke 3 énergie, dort un tour, puis se réveille et verrouille toute région où vous menez." },
  drowsivole: { epithet: "À moitié endormi", blurb: "Dort un tour, puis se réveille et verrouille vos régions. Éveillé, gagne 3 énergie quand l'adversaire verrouille une région où il se trouve." },
  lullabird: { epithet: "Douce berceuse", blurb: "Dort un tour, puis se réveille et verrouille vos régions. Au gel, les régions à égalité où il se trouve basculent en votre faveur." },
  dreamnewt: { epithet: "Qui s'endort", blurb: "Stocke 2 énergie, dort deux tours, puis se réveille et verrouille vos régions. Une frappe lente et lourde." },
  nutsquirrel: { epithet: "Fourrageur", blurb: "Stocke 2 énergie à la pose." },
  acorncache: { epithet: "Amasseur", blurb: "Stocke 4 énergie à la pose." },
  sunbeetle: { epithet: "Patient", blurb: "Stocke 1 énergie, et 3 de plus chaque fois que l'adversaire verrouille une région où il se trouve." },
  tallykit: { epithet: "Compteur", blurb: "Stocke 2 énergie pour chaque mine que vous possédez." },
  sunmoth: { epithet: "Au soleil", blurb: "Stocke 3 énergie à la pose." },
  emberfinch: { epithet: "Amadou", blurb: "Stocke 2 énergie, et 3 de plus chaque fois que l'adversaire verrouille une région où il se trouve." },
  pricklehog: { epithet: "Piquant", blurb: "L'adversaire ne peut pas verrouiller une région en la complétant tant que vous y tenez une case." },
  shellclam: { epithet: "Aube", blurb: "Au gel du jeu, les régions à égalité où vous tenez une case basculent en votre faveur." },
  barknewt: { epithet: "Repoussant", blurb: "Une Taupe ne peut pas le prendre, et tout autre retrait ne fait que l'écarter un tour." },
  thornpod: { epithet: "Protecteur", blurb: "Payez de l'énergie pour poser une mine (jusqu'à 3) : l'adversaire ne peut pas y jouer avant de la déminer, et elle compte comme une case à vous." },
  quillhog: { epithet: "Hérissé", blurb: "Chacune de vos mines compte double pour tenir une région." },
  barkmole: { epithet: "Retranché", blurb: "L'adversaire ne peut pas verrouiller une région en la complétant tant que vous y tenez une case, et tout retrait ne fait que l'écarter un tour." },
  swiftwren: { epithet: "Agité", blurb: "En posant ce chiffre, vous pouvez payer de l'énergie pour poser un second chiffre le même tour." },
  digmole: { epithet: "Fouisseur", blurb: "Payez de l'énergie pour poser ce chiffre sur un chiffre non permanent de l'adversaire dans une région disputée, le retirant." },
  wildlark: { epithet: "Ascendant", blurb: "Payez de l'énergie pour poser ce chiffre en ignorant la règle ligne/colonne/boîte (mais pas pour compléter une région)." },
  bombkit: { epithet: "Pétillant", blurb: "Vos mines coûtent 2 de moins à poser." },
  joltjay: { epithet: "Nerveux", blurb: "En posant ce chiffre, vous pouvez payer de l'énergie pour en poser un second le même tour, et il stocke 1 énergie à la pose." },
  sparkpaw: { epithet: "Statique", blurb: "Payez de l'énergie pour poser ce chiffre en ignorant les règles, ou pour le poser sur un chiffre non permanent de l'adversaire dans une région disputée, le retirant." },
};

const ZH: Lang = {
  boulderpup: { epithet: "稳如磐石", blurb: "它的格子是永久的，无法被移动或移除。" },
  mossback: { epithet: "古林", blurb: "它的每个格子在争夺区域时按两倍计算。" },
  slumberstone: { epithet: "落定中", blurb: "落定时沉睡一回合，之后变为永久。" },
  mudpaw: { epithet: "扎根", blurb: "对局冻结时，你在其中有它一个格子的平局区域归你。" },
  slatetusk: { epithet: "基岩", blurb: "它的格子是永久的，落子时储存 1 点能量。" },
  lichenox: { epithet: "缓慢蔓延", blurb: "扎根时沉睡一回合，之后它的每个格子在争夺区域时按两倍计算。" },
  breezefinch: { epithet: "轻浮", blurb: "它的格子可以跳到相邻的空格。" },
  tumbleweed: { epithet: "滚动", blurb: "它的格子可以跳跃，落子时储存 1 点能量以支付跳跃。" },
  glidewing: { epithet: "翱翔", blurb: "它的格子可以跳跃，且可以斜向跳。" },
  driftmink: { epithet: "掠行", blurb: "它的格子可以跳跃，落子时储存 2 点能量。" },
  galepup: { epithet: "阵风", blurb: "它的格子可以跳跃，也能斜跳，落子时储存 1 点能量。" },
  dandypuff: { epithet: "无重", blurb: "它的格子可以跳跃，任何移除只会让它离场一回合而非被拿走。" },
  snoozemouse: { epithet: "困倦", blurb: "沉睡一回合，然后醒来并锁定你领先的它的任一区域。" },
  fogkit: { epithet: "朦胧", blurb: "沉睡两回合，然后醒来并锁定你领先的它的任一区域。延迟的猛扑。" },
  dozderling: { epithet: "瞌睡采集者", blurb: "储存 3 点能量，沉睡一回合，然后醒来并锁定你领先的它的任一区域。" },
  drowsivole: { epithet: "半睡", blurb: "沉睡一回合，然后醒来并锁定你领先的区域。醒来后，当对手锁定它所在的区域时获得 3 点能量。" },
  lullabird: { epithet: "轻歌", blurb: "沉睡一回合，然后醒来并锁定你领先的区域。冻结时，它所在的平局区域归你。" },
  dreamnewt: { epithet: "入眠", blurb: "储存 2 点能量，沉睡两回合，然后醒来并锁定你领先的区域。缓慢而沉重的猛扑。" },
  nutsquirrel: { epithet: "采集者", blurb: "落子时储存 2 点能量。" },
  acorncache: { epithet: "囤积者", blurb: "落子时储存 4 点能量。" },
  sunbeetle: { epithet: "耐心", blurb: "储存 1 点能量，每当对手锁定它所在的区域时再获得 3 点。" },
  tallykit: { epithet: "计数者", blurb: "你每有一颗地雷，它就储存 2 点能量。" },
  sunmoth: { epithet: "晒太阳", blurb: "落子时储存 3 点能量。" },
  emberfinch: { epithet: "引火", blurb: "储存 2 点能量，每当对手锁定它所在的区域时再获得 3 点。" },
  pricklehog: { epithet: "带刺", blurb: "只要你在某区域有一个格子，对手就无法通过完成它来锁定。" },
  shellclam: { epithet: "晨光", blurb: "对局冻结时，你有一个格子的平局区域归你。" },
  barknewt: { epithet: "重生", blurb: "鼹鼠无法拿走它，其他移除只会让它离场一回合。" },
  thornpod: { epithet: "守卫", blurb: "花费能量埋一颗地雷（最多 3 颗）：对手清除前无法在此落子，且算作你占有的格子。" },
  quillhog: { epithet: "竖刺", blurb: "你的每颗地雷在争夺区域时按两倍计算。" },
  barkmole: { epithet: "掩体", blurb: "只要你在某区域有一个格子，对手就无法通过完成它来锁定，且任何移除只会让它离场一回合。" },
  swiftwren: { epithet: "躁动", blurb: "落下这个数字时，你可以花费能量在同一回合再落一个数字。" },
  digmole: { epithet: "掘地", blurb: "花费能量把这个数字落在争夺区域中对手的非永久数字上，将其移除。" },
  wildlark: { epithet: "上升", blurb: "花费能量无视行、列、宫规则落下这个数字（但不能用于完成区域）。" },
  bombkit: { epithet: "嘶嘶作响", blurb: "你埋地雷少花 2 点能量。" },
  joltjay: { epithet: "抽动", blurb: "落下这个数字时，可花费能量在同一回合再落一个，落子时储存 1 点能量。" },
  sparkpaw: { epithet: "静电", blurb: "花费能量无视规则落下这个数字，或将其落在争夺区域中对手的非永久数字上把它移除。" },
};

const AR: Lang = {
  boulderpup: { epithet: "راسخ", blurb: "خاناته دائمة. لا شيء يستطيع تحريكها أو إزالتها." },
  mossback: { epithet: "غابة عتيقة", blurb: "كل خانة من خاناته تُحسب مرتين للسيطرة على منطقة." },
  slumberstone: { epithet: "يستقر", blurb: "ينام دورًا وهو يستقر، ثم يصبح دائمًا." },
  mudpaw: { epithet: "مغروس", blurb: "عند تجمّد اللعب، المناطق المتعادلة التي تملك فيها إحدى خاناته تؤول لصالحك." },
  slatetusk: { epithet: "صخر الأساس", blurb: "خاناته دائمة، ويخزّن 1 طاقة عند الوضع." },
  lichenox: { epithet: "انتشار بطيء", blurb: "ينام دورًا وهو يتجذّر، ثم تُحسب كل خانة من خاناته مرتين للسيطرة على منطقة." },
  breezefinch: { epithet: "متقلّب", blurb: "يمكن لخاناته القفز إلى خانة فارغة مجاورة." },
  tumbleweed: { epithet: "متدحرج", blurb: "يمكن لخاناته القفز، ويخزّن 1 طاقة عند الوضع لدفع تكلفة القفز." },
  glidewing: { epithet: "محلّق", blurb: "يمكن لخاناته القفز، وقفزاته قد تكون قطرية أيضًا." },
  driftmink: { epithet: "منزلق", blurb: "يمكن لخاناته القفز، ويخزّن 2 طاقة عند الوضع." },
  galepup: { epithet: "هبّة ريح", blurb: "يمكن لخاناته القفز، قطريًا أيضًا، ويخزّن 1 طاقة عند الوضع." },
  dandypuff: { epithet: "بلا وزن", blurb: "يمكن لخاناته القفز، وأي إزالة تُبعده دورًا واحدًا فقط بدل أخذه." },
  snoozemouse: { epithet: "نعسان", blurb: "ينام دورًا، ثم يستيقظ ويقفل أي منطقة من مناطقه تتقدّم فيها." },
  fogkit: { epithet: "ضبابي", blurb: "ينام دورين، ثم يستيقظ ويقفل أي منطقة من مناطقه تتقدّم فيها. ضربة مؤجّلة." },
  dozderling: { epithet: "جامع نعسان", blurb: "يخزّن 3 طاقة، ينام دورًا، ثم يستيقظ ويقفل أي منطقة من مناطقه تتقدّم فيها." },
  drowsivole: { epithet: "نصف نائم", blurb: "ينام دورًا، ثم يستيقظ ويقفل مناطقك. بعد الاستيقاظ، يكسب 3 طاقة كلما قفل الخصم منطقة هو فيها." },
  lullabird: { epithet: "تهليلة", blurb: "ينام دورًا، ثم يستيقظ ويقفل مناطقك. عند التجمّد، المناطق المتعادلة التي هو فيها تؤول لصالحك." },
  dreamnewt: { epithet: "يغفو", blurb: "يخزّن 2 طاقة، ينام دورين، ثم يستيقظ ويقفل مناطقك. ضربة بطيئة ثقيلة." },
  nutsquirrel: { epithet: "جامع", blurb: "يخزّن 2 طاقة عند الوضع." },
  acorncache: { epithet: "مكتنِز", blurb: "يخزّن 4 طاقة عند الوضع." },
  sunbeetle: { epithet: "صبور", blurb: "يخزّن 1 طاقة، و3 إضافية كلما قفل الخصم منطقة هو فيها." },
  tallykit: { epithet: "عدّاد", blurb: "يخزّن 2 طاقة عن كل لغم تملكه." },
  sunmoth: { epithet: "متشمّس", blurb: "يخزّن 3 طاقة عند الوضع." },
  emberfinch: { epithet: "قدّاحة", blurb: "يخزّن 2 طاقة، و3 إضافية كلما قفل الخصم منطقة هو فيها." },
  pricklehog: { epithet: "شائك", blurb: "لا يستطيع الخصم قفل منطقة بإكمالها ما دمت تملك خانة فيها." },
  shellclam: { epithet: "فجر", blurb: "عند تجمّد اللعب، المناطق المتعادلة التي تملك فيها خانة تؤول لصالحك." },
  barknewt: { epithet: "متجدّد", blurb: "لا يستطيع الخُلد أخذه، وأي إزالة أخرى تُبعده دورًا واحدًا فقط." },
  thornpod: { epithet: "حارس", blurb: "ادفع طاقة لزرع لغم (حتى 3): لا يستطيع الخصم الوضع هناك حتى يزيله، ويُحسب خانة لك." },
  quillhog: { epithet: "منتفش", blurb: "كل لغم لك يُحسب مرتين للسيطرة على منطقة." },
  barkmole: { epithet: "متحصّن", blurb: "لا يستطيع الخصم قفل منطقة بإكمالها ما دمت تملك خانة فيها، وأي إزالة تُبعده دورًا واحدًا فقط." },
  swiftwren: { epithet: "لا يهدأ", blurb: "عند وضع هذا الرقم يمكنك دفع طاقة لوضع رقم ثانٍ في الدور نفسه." },
  digmole: { epithet: "حفّار", blurb: "ادفع طاقة لوضع هذا الرقم فوق رقم غير دائم للخصم في منطقة متنازع عليها، فتزيله." },
  wildlark: { epithet: "صاعد", blurb: "ادفع طاقة لوضع هذا الرقم متجاهلًا قاعدة الصف والعمود والمربع (لكن ليس لإكمال منطقة)." },
  bombkit: { epithet: "يطقطق", blurb: "ألغامك تكلّف 2 أقل لزرعها." },
  joltjay: { epithet: "متوتّر", blurb: "عند وضع هذا الرقم يمكنك دفع طاقة لوضع رقم ثانٍ في الدور نفسه، ويخزّن 1 طاقة عند الوضع." },
  sparkpaw: { epithet: "ساكن كهربائي", blurb: "ادفع طاقة لوضع هذا الرقم متجاهلًا القواعد، أو لوضعه فوق رقم غير دائم للخصم في منطقة متنازع عليها فتزيله." },
};

const OVERRIDES: Record<string, Lang> = { es: ES, fr: FR, zh: ZH, ar: AR };

export function critterText(lang: string, id: CreatureId): Entry {
  const o = OVERRIDES[lang]?.[id];
  if (o) return o;
  const d = ROSTER[id];
  return { epithet: d.epithet, blurb: d.blurb };
}
